# Generated by Django 4.2.21 on 2025-06-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="supabase_user_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
