# Generated by Django 5.0.4 on 2025-12-11 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Movie", "0002_alter_customuser_supabase_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="supabase_user_id",
        ),
        migrations.CreateModel(
            name="my_subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("contract_date", models.DateField()),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
